baseURL = "https://theresacheng.github.io/"
languageCode = "en-us"
title = "Theresa W Cheng"
theme = "hugo-lodi-theme"
googleAnalytics = "UA-XXXXXXXX-Y"
enableEmoji = true 
publishDir = "/Users/theresacheng/Dropbox (PfeiBer Lab)/Cheng/code/theresacheng.github.io"

[params]
    theme_color = "#574CDD"
    description = "An academic website for Theresa W. Cheng"
    description_photo = "portfolio.jpg"
    favicon = "favicon.png"
    logo = "tc_logo.png"
    email = "tcheng@uoregon.edu"
    #facebook = "lex.collado"
    twitter = "cecily_cardew"
    github = ""
    researchgate = "blah"
    #dribbble = "alexiscollado"
    #linkedin = ""
    #medium = "ahvccollado"

[params.nav]
    enable = true

[params.hero]
    enable = true
    avatar = "tc_avatar.jpg"
    subtitle = "Hello! I'm Theresa W. Cheng, a PhD student at the University of Oregon"
    hero_right = ["**I'm a developmental cognitive neuroscientist studying stress, puberty, and social relationships in adolescence.**  \n  \n  I'm broadly interested in how adolescents learn from their social environments, how stress and puberty shape neurobiological systems supporting social learning and motivation, and the potential to leverage these understandings to support health and well-being in vulnerable youth. \n  \n  Currently, I'm an NIH/NCATS pre-doctoral fellow at the Oregon Clinical and Translational Research Institute and a Millennium Scholar with the Society for Research in Child Development. I also co-organize the Eugene, OR [pod](https://sites.google.com/view/500ws-eugene/home) of [500 Women Scientists](https://500womenscientists.org/) and represent my fellow graduate students in the [Graduate Teaching Fellows Federation](http://gtff3544.net/) at the University of Oregon."]
    
[params.case_studies]
    enable = true
    title = "Blog Posts"
    
[params.process]
enable = false
title = "My Process"
subtitle = "Full Process Design"

[params.footer]
    enable = true
